version: '3'
services:
  db:
    image: postgres:12.6-alpine
    container_name: db
    environment:
      POSTGRES_DB: wslearn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/pgdata
      volumes:
        /var/lib/postgresql/data
    restart: on-failure

  service:
    image: bolgovid/wslearn
    container_name: service
    ports:
      - "8000:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wslearn
    depends_on:
      - db
    command: java -jar /app.jar
    restart: on-failure

#  ui:
#    image: bolgovid/wslearn:ui
#    container_name: ui
#    volumes:
#      - .:/usr/app/x
#      - /usr/app/node_modules
#    ports:
#      - "8090:8080"
#    depends_on:
#      - service
#    command: npm run serve
#    restart: on-failure
