kind: Service
apiVersion: v1
metadata:
  name: wslearn-back
  labels:
    name: wslearn-back
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: wslearn-back
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wslearn-back
spec:
  selector:
    matchLabels:
      app: wslearn-back
  replicas: 3
  template:
    metadata:
      labels:
        app: wslearn-back
    spec:
      containers:
        - name: wslearn-back
          image: bolgovid/wslearn
          ports:
            - containerPort: 8080
          env:   # Setting Environment all Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials # Secret Name
                  key: postgres_user
            - name: POSTGRES_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
